# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  ______            _           _              _______   _            _____                    #
# |  ____|          | |         (_)            |__   __| (_)          / ____|                   #
# | |__  __  ___ __ | | ___  ___ _  ___  _ __  ___| |_ __ _ _ __ ___ | |  __ _ __ __ _ ___ ___  #
# |  __| \ \/ / '_ \| |/ _ \/ __| |/ _ \| '_ \/ __| | '__| | '_ ` _ \| | |_ | '__/ _` / __/ __| #
# | |____ >  <| |_) | | (_) \__ \ | (_) | | | \__ \ | |  | | | | | | | |__| | | | (_| \__ \__ \ #
# |______/_/\_\ .__/|_|\___/|___/_|\___/|_| |_|___/_|_|  |_|_| |_| |_|\_____|_|  \__,_|___/___/ #
#             | |                                                                               #
#             |_|                                                                    by JustEli #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Disable entities that aren't mobs--like item frames and armor stands--to take damage from
#  explosions. So, disable damage done by explosions to those.
disable-damage-to-non-mobs: true

# Should trimming happen for any type of explosions, or just creepers?
only-enable-for-creepers: false

# Set values down here to what you want the global default to be for the section
#  'transform-blocks'. You can change the value per block, but these will be the
#  default, and can be overridden by adding it to the block section you don't
#  want the default value to apply for.
default-values:
  # Enable block modifications by explosions under this Y-level only.
  maximum-y-level: 512
  # Disable explosion block modification in GriefPrevention claims. Note that, down the
  #  config, it will be overridden for some blocks where it is set to 'true'.
  disable-in-claims: false
  # Disable block transformations by explosions in WorldGuard regions.
  #  Admin claims of GriefPrevention also count as regions.
  disable-in-regions: true

# Blocks that should be affected (transformed) by explosions are defined down here.
#  For example:
#  - 'stone':          is a block, so this is triggered when a stone block explodes
#  - 'etg:trimmable':  is not a block, so its block-list is defined down the config
# All allowed materials: https://jd.papermc.io/paper/org/bukkit/Material.html
#  If an invalid Material is used, its block-list must be defined at 'definitions'.
transform-blocks:
  # Not a Material (etg:trimmable), so its blocks are defined at 'definitions' down
  #  the config. In this case, it's: GRASS_BLOCK and MYCELIUM. What to do with these
  #  blocks when a creeper explosion effects these blocks?
  'etg:trimmable':
    # Convert the affected blocks (in this case GRASS_BLOCK and MYCELIUM) into ...
    conversion:
      # The affected block by the explosion will be converted to ...
      'coarse_dirt': 0.08   # 8% coarse dirt (can use a hoe in-game to make it dirt!)
      'dirt': 0.92          # and 92% dirt
  # This is a Material (STONE), so it is not defined down the config.
  'stone':
    # This value was already defined at 'default-values', and default set to 'false', but we
    #  want to override it for this block and only have it under sea-level for STONE.
    maximum-y-level: 64
    conversion:
      'infested_cobblestone': 0.01
      'cobblestone': 0.99
  'snow':
    conversion:
      # All snow layers will be broken (particle effects play) and set to AIR.
      'air': 1.00
  'etg:grasses':
    conversion:
      'air': 1.00
  'etg:leaves':
    # Override this value from its default (false), and set it to not break leaves by
    #  explosions in GriefPrevention claims.
    disable-in-claims: true
    conversion:
      'air': 1.00
  'etg:flowers':
    disable-in-claims: true
    conversion:
      'air': 1.00
  'etg:glass_panes':
    disable-in-claims: true
    conversion:
      # The exploded block will be converted to 20% air and 80% stay intact.
      'air': 0.20

# The definitions for non-existing lists of blocks, used above here.
definitions:
  'etg:trimmable':
    - grass_block
    - podzol
    - mycelium
  'etg:leaves':
    - oak_leaves
    - spruce_leaves
    - birch_leaves
    - jungle_leaves
    - acacia_leaves
    - dark_oak_leaves
    - mangrove_leaves
    - cherry_leaves
    - azalea_leaves
    - flowering_azalea_leaves
    - pale_oak_leaves
  'etg:grasses':
    - short_grass
    - fern
    - large_fern
    - tall_grass
    - dead_bush
    - leaf_litter
    - bush
    - firefly_bush
    - short_dry_grass
    - tall_dry_grass
  'etg:flowers':
    - dandelion
    - poppy
    - blue_orchid
    - allium
    - azure_bluet
    - red_tulip
    - white_tulip
    - orange_tulip
    - pink_tulip
    - oxeye_daisy
    - cornflower
    - lily_of_the_valley
    - sunflower
    - lilac
    - rose_bush
    - peony
    - pink_petals
    - pitcher_plant
    - torchflower_crop
    - oak_sapling
    - spruce_sapling
    - birch_sapling
    - jungle_sapling
    - acacia_sapling
    - dark_oak_sapling
    - brown_mushroom
    - red_mushroom
    - potatoes
    - wheat
    - carrots
    - melon_stem
    - pumpkin_stem
    - beetroots
    - pale_oak_sapling
    - closed_eyeblossom
    - open_eyeblossom
    - wildflowers
    - cactus_flower
  'etg:glass_panes':
    - glass_pane
    - white_stained_glass_pane
    - orange_stained_glass_pane
    - magenta_stained_glass_pane
    - light_blue_stained_glass_pane
    - yellow_stained_glass_pane
    - lime_stained_glass_pane
    - pink_stained_glass_pane
    - gray_stained_glass_pane
    - light_gray_stained_glass_pane
    - cyan_stained_glass_pane
    - purple_stained_glass_pane
    - blue_stained_glass_pane
    - brown_stained_glass_pane
    - green_stained_glass_pane
    - red_stained_glass_pane
    - black_stained_glass_pane
