main: '${project.groupId}.${project.name}'
name: '${project.name}'
version: '${project.version}'
authors: [JustEli]
website: '${project.url}'
api-version: '${versions.minecraft.spigot}'
commands:
  'etg':
    permission: 'etg.admin'
    description: 'Admin command to manage ExplosionsTrimGrass.'
